# Generated by Django 2.0.7 on 2018-07-28 17:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('author', models.CharField(max_length=15)),
                ('msg', models.CharField(max_length=300)),
                (
                    'created_date',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('comment_visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=70)),
                ('body', models.TextField()),
                ('summary', models.CharField(max_length=100)),
                (
                    'created_date',
                    models.DateTimeField(
                        default=datetime.datetime(
                            2018, 7, 28, 17, 55, 3, 42423, tzinfo=utc
                        )
                    ),
                ),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='blog.Post',
            ),
        ),
    ]
