# Generated by Django 2.0.7 on 2018-08-03 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [('blog', '0002_auto_20180803_1552')]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(
                default=datetime.datetime(2018, 8, 3, 11, 0, 59, 956213, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
