# Generated by Django 2.1.1 on 2018-09-16 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [('blog', '0010_auto_20180916_2159')]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(
                default=datetime.datetime(2018, 9, 16, 16, 29, 11, 155854, tzinfo=utc)
            ),
        )
    ]
