# Generated by Django 2.1.7 on 2019-06-03 05:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190601_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 5, 56, 44, 241352, tzinfo=utc)),
        ),
    ]
