# Generated by Django 2.2.13 on 2020-09-12 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200525_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 14, 14, 47, 645915, tzinfo=utc)),
        ),
    ]
